CRB-252 Reset publishing after a new chain head is committed
gluwa/Creditcoin-Consensus-Rust pull request #10
Opened 2021-10-27 18:21 UTC by CAGS295

Prior to this update the consensus could only mine if isolated. Publishing was reset after successfully publishing a block instead of after a block being committed. This could end in the consensus crashing.

2021-10-28 18:31 UTC, atodorov reviewed
I'm not seeing any unit tests being added for the newly introduced code, see Codecov comments on the Files change tab.  I'm not sure what to make of the current PR.

2021-11-12 23:25 UTC, nathanwhit reviewed
Looks good to me overall, just one nit. (It can also be left to a follow-up PR if you want).

2021-11-12 23:25 UTC, nathanwhit commented on src/futures/update_stream.rs
> +    let committer = UpdateStream::toggle_on_reactor(commit_flag.clone()).fuse();
Instead of checking the commit flag in a loop, why not use something like [Notify](https://docs.rs/tokio/1.13.0/tokio/sync/struct.Notify.html) to wait for the event asynchronously? That way the task will only wake up once the event has occurred (the new chainhead arrives), which is more efficient. It's also a bit clearer in intent than a boolean flag IMO.

2021-11-19 20:17 UTC, atodorov requested changes
Needs rebase + conflict resolution.

2021-11-19 21:03 UTC, CAGS295 commented on src/futures/update_stream.rs
> +    let committer = UpdateStream::toggle_on_reactor(commit_flag.clone()).fuse();
Agreed, opened a ticket for later.

2021-11-23 17:19 UTC, closed without merging