CRB-311 expected difficulty
gluwa/Creditcoin-Consensus-Rust pull request #39
Opened 2022-01-20 16:55 UTC by CAGS295

Using the actual difficulty as minimum difficulty is not stable. Use the expected difficulty as minimum difficulty.

The current publishing interval won’t let expected difficulty increase. Reduced it below sound publishing parameters.

Tests:

Algorithm version needs a bump in on-chain settings. Tested locally using battery energy options to increase/decrease hashing power and observe diff adjustment.

two-node setup not tested.

Publishing interval reduced to 500ms, low risk of affecting the publisher event loop. The publisher event loop could be simplified more in the future for performance and maintainability if the publishing interval is not required anymore.

2022-01-20 17:50 UTC, atodorov requested changes
ATM test code doesn't look appropriate to me or I don't understand the intention here.

In addition to that the Jira ticket itself uses a confusing language and when language is confusing I can't make any judgement about the changes or the proposed tests.

Jira title says "Store minimum difficulty", while description says "Use the expected difficulty as minimum difficulty." This raises the following questions to make things clear:
- What is actual/minimum/expected difficulty and how do they differ ? 
- Store vs. Use - these are different verbs denoting different actions. What was the original intention of the ticket? What's the desired behavior? 


-

2022-01-20 17:50 UTC, atodorov commented on src/engine.rs
> +      let time_til_publishing = Duration::from_millis(500);
This is a change in behavior which sounds like it needs to be a change in configuration? I need more background here to understand what's going on.

2022-01-20 17:50 UTC, atodorov commented on src/miner/miner.rs
> +    //the second answer if any is guaranteed to be higher than the expected difficulty but the expected diff should stay the same
I see assertions about the state of realized difficulty and then comparing two instances of realized difficulty but nothing asserting on the state of expected difficulty. How can we check that? It sounds like we need one more assertion to make sure expected difficulty did not change.

2022-01-20 17:50 UTC, atodorov commented on src/miner/worker.rs
> +            current_difficulty = challenge.difficulty.saturating_sub(1);
I see the `current_difficulty` variable being updated here and on line 106 but I don't see the variable being used anywhere else afterwards so I'm not sure what to make of it.

2022-01-20 17:50 UTC, atodorov commented on src/miner/miner.rs
> +    assert!(realized_difficulty > challenge.difficulty);
I'm not sure what the above 3 lines are trying to accomplish. If the subject under test is `Worker::task()` which internally uses `is_valid_proof_of_work()` then inside the test we should not be calling directly `is_valid_proof_of_work()` and using its results unless I am missing something. 

But changing behavior in one function then calling another one to assert on its results doesn't look like the appropriate test. It looks like switching or mixing the subject under test.

2022-01-20 19:11 UTC, atodorov commented on src/engine.rs
> +      let time_til_publishing = Duration::from_millis(500);
FTR the config value isn't necessary inside this function anymore. Changing actual to expected difficulty goes hand-in-hand with the hard-coded interval above.

2022-01-20 19:14 UTC, atodorov commented on src/miner/worker.rs
> +            current_difficulty = challenge.difficulty.saturating_sub(1);
I didn't see the loop on line 90.

2022-01-20 19:17 UTC, atodorov commented on src/miner/miner.rs
> +    assert!(realized_difficulty > challenge.difficulty);
FTR: `is_valid_proof_of_work()` is a helper function which returns a tuple, bool and the leading number of zeroes in the solution (which we call the difficulty). 

Here it is used to calculate the difficulty of the returned solution (`hash` variable).

2022-01-20 19:19 UTC, atodorov commented on src/miner/miner.rs
> +    //the second answer if any is guaranteed to be higher than the expected difficulty but the expected diff should stay the same
"expected difficulty" is what goes as input, in this case `challenge.difficulty`.

2022-01-20 19:22 UTC, atodorov approved these changes, later dismissed
After getting more info the proposed tests look good to me. They need a few more comments to make it more obvious what's going on. 

I'll wait for the comments and will do a follow-up test cleanup. 

I'll also cherry-pock 73b20dd599275fb01666b5f642a1de7acb5796e6 to appease Clippy if you don't do it yourself.

2022-01-27 12:06 UTC, atodorov submitted a review, later dismissed

2022-01-27 23:19 UTC, seandeneen-gluwa submitted a review, later dismissed
Line 122 of block_consensus.rs needs to be fixed, but the rest looks good.

2022-02-07 18:43 UTC, CAGS295 commented
> Line 122 of block_consensus.rs needs to be fixed, but the rest looks good.

Which one is that again?

2022-02-07 19:39 UTC, atodorov approved these changes

2022-02-07 23:30 UTC, vladimir-gluwa commented on src/engine.rs
> +      let time_til_publishing = Duration::from_millis(500);
Where the constant comes from?

2022-02-08 00:50 UTC, CAGS295 commented on src/engine.rs
> +      let time_til_publishing = Duration::from_millis(500);
Covered in detail on slack.

2022-02-08 01:38 UTC, vladimir-gluwa approved these changes

2022-02-08 16:22 UTC, merged